"use client";

console.warn(
  "⚠️ Avoid importing components from 'index.js' for better performance. This practice is deprecated and may be removed in the future."
);

export * as _Builtin from "./_Builtin";
export * from "./About";
export * from "./Banner";
export * from "./Button";
export * from "./Card";
export * from "./CardStack";
export * from "./Content";
export * from "./devlink";
export * from "./devlinkContext";
export * from "./DevLinkProvider";
export * from "./Faq";
export * from "./FeaturedProjects";
export * from "./Features";
export * from "./FeaturesRichText";
export * from "./Footer";
export * from "./FormCta";
export * from "./GlobalStyles";
export * from "./ImageSection";
export * from "./interactions";
export * from "./List";
export * from "./LogoBanner";
export * from "./LogoParty";
export * from "./Navbar";
export * from "./NavbarTrigger";
export * from "./OldCtaSection";
export * from "./OldHeader";
export * from "./OnboardingForm";
export * from "./Points";
export * from "./Preloader";
export * from "./PremiumPartnerBadge";
export * from "./Pricing";
export * from "./Process";
export * from "./ProcessOld";
export * from "./QuoteCta";
export * from "./RelatedBlogs";
export * from "./ResourcesCard";
export * from "./RichText";
export * from "./Services";
export * from "./ServicesCard";
export * from "./ServicesOld";
export * from "./SocialList";
export * from "./SpacerHuge";
export * from "./SpacerLarge";
export * from "./SpacerMedium";
export * from "./SpacerMedLarge";
export * from "./SpacerMedSmall";
export * from "./SpacerSmall";
export * from "./SpacerXlarge";
export * from "./SpacerXsmall";
export * from "./SpacerXxlarge";
export * from "./SpacerXxsmall";
export * from "./Steps";
export * from "./Team";
export * from "./TestimonialCard";
export * from "./TestimonialClientWrapper";
export * from "./Testimonials";
export * from "./Transition";
export * from "./utils";
export * from "./values/Builtin/formatNumber";
